spring:
  application:
    name: zipcodesearch
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/zipcode_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true