CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS "zipcodes" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"zipcode" VARCHAR(15) NOT NULL,
	"street" VARCHAR(150) NULL,
	"complement" VARCHAR(100) NULL,
	"unit" VARCHAR(50) NULL,
	"neighborhood" VARCHAR(100) NULL,
	"location" VARCHAR(50) NOT NULL,
	"state_code" VARCHAR(2) NOT NULL,
	"state" VARCHAR(50) NOT NULL,
	"region" VARCHAR(50) NOT NULL,
	"ibge" VARCHAR(7) NOT NULL,
	"gia" VARCHAR(4) NULL,
	"ddd" VARCHAR(2) NOT NULL,
	"siafi" VARCHAR(4) NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE UNIQUE INDEX "zipcodes_index_zipcode"
ON "zipcodes" ("zipcode");
CREATE INDEX "zipcodes_index_ibge"
ON "zipcodes" ("ibge");
CREATE INDEX "zipcodes_index_siafi"
ON "zipcodes" ("siafi");

CREATE INDEX zipcodes_street_trgm
ON zipcodes USING GIN (street gin_trgm_ops);